#!/bin/bash
# ============================================================
# CodeRoute Guinée — Generate strong secrets for production
# ============================================================
# Generates a .env.production file with cryptographically secure
# random secrets. The operator then fills in the integration
# credentials (Orange SMS, MoMo, SMTP, DATABASE_URL).
#
# Usage:
#   bash scripts/generate-secrets.sh > .env.production
#   # Then edit .env.production to fill in real integration creds
# ============================================================

set -euo pipefail

# Generate 32-byte hex secrets (64 chars)
gen_secret() {
  openssl rand -hex 32
}

# Generate a 16-char alphanumeric password (no special chars for easy copy/paste)
gen_password() {
  openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 16
}

echo "# ============================================================"
echo "# CodeRoute Guinée — Production Environment"
echo "# ============================================================"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "#"
echo "# This file was auto-generated by scripts/generate-secrets.sh."
echo "# The secrets below are NEW and random — do not commit this file."
echo "# Fill in the remaining INTEGRATION vars (DB, SMTP, Orange, MoMo)."
echo "# ============================================================"
echo ""
echo "# ─── Runtime ──────────────────────────────────────────────"
echo "NODE_ENV=\"production\""
echo "NEXT_PUBLIC_APP_URL=\"https://coderoute-gn.org\"  # CHANGE to your real domain"
echo ""
echo "# ─── Database (PostgreSQL REQUIRED in production) ─────────"
echo "# Use the connection string from your PostgreSQL provider"
echo "# (Supabase, Neon, RDS, or self-hosted Docker)."
echo "DATABASE_URL=\"postgresql://USER:PASSWORD@HOST:5432/coderoute?schema=public\""
echo ""
echo "# ─── Cryptographic secrets (auto-generated) ──────────────"
echo "# These are used to sign session cookies, JWTs, and CSRF tokens."
echo "# Rotate them = invalidate all sessions (force re-login)."
echo "SESSION_SECRET=\"$(gen_secret)\""
echo "JWT_SECRET=\"$(gen_secret)\""
echo "CSRF_SECRET=\"$(gen_secret)\""
echo ""
echo "# ─── Email (SMTP) ────────────────────────────────────────"
echo "# Required to send welcome emails, password resets, exam reminders."
echo "# Recommended providers: Brevo (free 300/day), Mailgun, AWS SES."
echo "SMTP_HOST=\"\""
echo "SMTP_PORT=\"587\""
echo "SMTP_SECURE=\"false\""
echo "SMTP_USER=\"\""
echo "SMTP_PASS=\"\""
echo "SMTP_FROM_NAME=\"CodeRoute Guinée\""
echo "SMTP_FROM_EMAIL=\"noreply@coderoute-gn.org\""
echo ""
echo "# ─── SMS — Orange OAuth2 ──────────────────────────────────"
echo "# Get credentials at https://developer.orange.com"
echo "# Leave blank to keep SMS in console mode (logs to stdout)."
echo "SMS_PROVIDER=\"orange\""
echo "ORANGE_SMS_CLIENT_ID=\"\""
echo "ORANGE_SMS_CLIENT_SECRET=\"\""
echo "ORANGE_SMS_SENDER_ADDRESS=\"\""
echo "ORANGE_SMS_API_BASE=\"https://api.orange.com\""
echo ""
echo "# ─── Mobile Money ────────────────────────────────────────"
echo "# Provider must be one of: mock | orange | mtn | celcom"
echo "# Get credentials from each operator's merchant portal."
echo "MOMO_PROVIDER=\"mock\"  # ← CHANGE to real provider when creds are ready"
echo "MOMO_API_KEY=\"\""
echo "MOMO_API_SECRET=\"\""
echo "MOMO_MERCHANT_ID=\"\""
echo ""
echo "# ─── Initial super-admin bootstrap ───────────────────────"
echo "# Used ONCE by scripts/bootstrap-admin.ts to create the first"
echo "# admin account. Delete these lines after first boot."
echo "BOOTSTRAP_ADMIN_EMAIL=\"admin@coderoute-gn.org\""
echo "BOOTSTRAP_ADMIN_PASSWORD=\"$(gen_password)\""
echo ""
echo "# ─── Optional: error monitoring ──────────────────────────"
echo "# Sentry DSN — get from https://sentry.io (free 5k events/month)"
echo "SENTRY_DSN=\"\""
echo "SENTRY_ENVIRONMENT=\"production\""
echo ""
echo "# ─── Rate limiting ───────────────────────────────────────"
echo "RATE_LIMIT_MAX=\"100\""
echo "RATE_LIMIT_WINDOW_MS=\"60000\""
echo ""
echo "# ─── Backups ─────────────────────────────────────────────"
echo "# Path where daily DB backups are stored (cron'd by scripts/backup-cron.sh)"
echo "BACKUP_DIR=\"/var/backups/coderoute\""
echo "BACKUP_RETENTION_DAYS=\"30\""
echo ""
echo "# ─── Cron secret ─────────────────────────────────────────"
echo "# Required for /api/cron/* endpoints. Generate a new one."
echo "CRON_SECRET=\"$(gen_secret)\""
